#!/bin/bash

echo "  "
BASEURL=$(echo "$1" | sed 's/\/seg\-.*//g')
URL=$BASEURL
FILE=foo
x=0
mkdir tmp
cd tmp
while :
do 
x=$(( $x + 1 ))
	URL="${BASEURL}/seg-${x}-v1-a1.ts"
	FILE="*seg-$x*"
	echo "file seg-$x.ts" >> filelist
	#echo $URL
	wget -q $URL -O "seg-$x.ts"
	if [ -s $FILE ]
	then
		echo -ne "Segment : $x done\r"
	else
		echo -e "\nSegment : $x not found, filename $FILE not found"
		break
	fi
done
echo "==================================="
echo "finnished downloading on Segment $x"
echo "starting mp4 conversion"
echo "==================================="

ffmpeg -loglevel 'fatal' -f concat -i filelist -c copy ../output.mp4
cd ..
rm -rf tmp
echo "All done!"

